name: Charm4py-cython

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
      - cron: '5 0 * * *'  # Runs at 00:05 UTC every day.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-charm4py
      run: |
        git fetch --unshallow # Need full repo for 'git describe' used by setup.py
        pip3 install setuptools cython greenlet numpy
        git clone https://github.com/UIUC-PPL/charm charm_src/charm
        export CHARM_EXTRA_BUILD_OPTS="--enable-error-checking"
        export CHARM_BUILD_PROCESSES=2
        python3 setup.py build_ext --inplace
        export PYTHONPATH="$PWD"
    - name: test-charm4py
      run: |
        git clone https://github.com/slm960323/task-bench.git
        cd task-bench
        pwd
        cd core
        make -j2
        export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
        cd ../../
        python3 -c "import sys;print(sys.path)"
        export PYTHONPATH="$PWD"
        export CHARM4PY_TEST_NUM_PROCESSES=2
        python3 -c "import sys;print(sys.path)"
        python3 auto_test.py
